### ISSUE TITLE
Include QGIS Integration tests in Travis

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#170]
We have enabled Travis test for core geonode.
However it is still using Geoserver backend.
We need to include QGIS Server in Travis so we can test it (integration tests and url)

# TODO List:

- [x] Fix rabbitmq for geoserver (need to put upstream)
- [x] Fix warning message for geofence (need to put upstream)
- [x] Ensure integration tests working
- [x] Set up OGC for QGIS Server? Used for csw tests.

**Comment by Gustry** [comment]
Do you know how you will set up this?
It might be interrsting.

I would say with 2 matrices. One for geoserver and one qgis (as a geonode can't have 2 backends). So it means you need to flag all tests in geonode with geoserver or qgis and disable them in each matrix?

**Comment by lucernae** [comment]
Yes, basically I need to give some kind of flag to tell which test relevant with which backend.
See #172 for some sample.

**Comment by lucernae** [comment]
Will close this, setting up OGC for QGIS Server is handled by other issues. #237
