### ISSUE TITLE
List of current failed Geonode's Integration tests

### ISSUE THREAD

**Issue by lucernae** [kartoza/geonode#172]
Based on running the tests in:
`geonode/tests/integration.py`

Listed below are all failed tests when using QGIS Server:

## GeoNodeMapTest
- [x] test_cascading_delete [@boney-bun][@lucernae] #248 
- [x] test_delete_layer [@boney-bun][@lucernae] #248
- [x] test_layer_delete_from_geoserver[@lucernae] #248
- [x] test_layer_replace [@boney-bun][@lucernae]
- [x] test_raster_upload [@boney-bun] [@ismailsunni] #239

## GeoNodePermissionsTest
- [x] test_unpublished [@boney-bun][@lucernae] #248

## GeoNodeThumbnailTest
- [x] test_layer_thumbnail [@lucernae]
- [x] test_map_thumbnail [@lucernae]

### geonode.maps.test

- [x] test_map_view [@lucernae] #235 
- [x] test_new_map_config [@lucernae] #235
- [x] test_fix_baselayers [@lucernae] #235

### geonode.security.tests

- [x] test_anonymous_permissions [@lucernae] #248
- [x] test_map_download [@lucernae] #248
- [x] test_not_superuser_permissions [@lucernae] #248

### geonode.geoserver.tests

We probably just skip this test, but needs to create the counterpart for qgis-server

- [x] test_feature_edit_check [@lucernae] #248
- [x] test_layer_acls [@lucernae] #248
- [x] test_resolve_user [@lucernae] #248
- [x] test_style_manager [@lucernae] #248
- [x] test_login_middleware [@lucernae] #248

### geonode.layers.tests

- [x] test_get_files #248

# Approach

Inspect each failed approach and see if it is relevant with QGIS Server. For example, test_layer_delete_from_geoserver seems irrelevant. In that case, we need to create some switch to disable the test if it is using QGIS Server backend. Otherwise, if it is relevant, fix it.

**Comment by lucernae** [comment]
Finally, we can close this.
